# Generated by Django 4.2.7 on 2026-01-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="业主姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "id_card",
                    models.CharField(max_length=18, unique=True, verbose_name="身份证号"),
                ),
                (
                    "wechat_openid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="微信OpenID",
                    ),
                ),
                (
                    "wechat_nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="微信昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="头像URL"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已认证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "业主",
                "verbose_name_plural": "业主",
                "db_table": "property_owner",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="单元号"
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="楼层")),
                ("room_number", models.CharField(max_length=20, verbose_name="房号")),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="面积(㎡)"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("residential", "住宅"),
                            ("commercial", "商业"),
                            ("garage", "车库"),
                            ("storage", "储藏室"),
                        ],
                        default="residential",
                        max_length=20,
                        verbose_name="房产类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("occupied", "自住"),
                            ("rented", "出租"),
                            ("vacant", "空置"),
                            ("renovation", "装修中"),
                        ],
                        default="vacant",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="房产描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="community.building",
                        verbose_name="所属楼栋",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="community.community",
                        verbose_name="所属小区",
                    ),
                ),
            ],
            options={
                "verbose_name": "房产",
                "verbose_name_plural": "房产",
                "db_table": "property_property",
                "ordering": ["community", "building", "unit", "floor", "room_number"],
                "unique_together": {("building", "unit", "floor", "room_number")},
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="租户姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("id_card", models.CharField(max_length=18, verbose_name="身份证号")),
                (
                    "wechat_openid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="微信OpenID",
                    ),
                ),
                (
                    "wechat_nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="微信昵称"
                    ),
                ),
                ("lease_start", models.DateField(verbose_name="租赁开始日期")),
                ("lease_end", models.DateField(verbose_name="租赁结束日期")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to="property.property",
                        verbose_name="租赁房产",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户",
                "verbose_name_plural": "租户",
                "db_table": "property_tenant",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnerProperty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("full", "完全所有权"),
                            ("shared", "共同所有"),
                            ("mortgage", "按揭中"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="所有权类型",
                    ),
                ),
                (
                    "ownership_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=5,
                        verbose_name="所有权比例(%)",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="是否主要房产"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="property.owner",
                        verbose_name="业主",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="property.property",
                        verbose_name="房产",
                    ),
                ),
            ],
            options={
                "verbose_name": "业主房产关联",
                "verbose_name_plural": "业主房产关联",
                "db_table": "property_owner_property",
                "unique_together": {("owner", "property")},
            },
        ),
    ]
