# Generated by Django 4.2.7 on 2026-01-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="source",
            field=models.CharField(
                choices=[
                    ("system", "系统导入"),
                    ("self_registered", "自行注册"),
                    ("admin_added", "管理员添加"),
                ],
                default="system",
                max_length=20,
                verbose_name="数据来源",
            ),
        ),
        migrations.AddField(
            model_name="owner",
            name="verification_status",
            field=models.CharField(
                choices=[("pending", "待审核"), ("approved", "已通过"), ("rejected", "已拒绝")],
                default="approved",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="id_card",
            field=models.CharField(
                blank=True, max_length=18, null=True, verbose_name="身份证号"
            ),
        ),
    ]
