# Generated by Django 4.2.7 on 2026-01-13 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "community",
            "0002_community_construction_area_community_contact_person_and_more",
        ),
        ("property", "0002_owner_source_owner_verification_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={
                "ordering": ["community", "building", "unit", "room_number"],
                "verbose_name": "房产",
                "verbose_name_plural": "房产",
            },
        ),
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={("building", "room_number")},
        ),
    ]
