# Generated by Django 4.2.7 on 2026-01-14 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "community",
            "0002_community_construction_area_community_contact_person_and_more",
        ),
        ("property", "0004_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="property",
            unique_together={("building", "unit", "floor", "room_number")},
        ),
    ]
