# Generated by Django 4.2.7 on 2026-01-06 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeChatUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "openid",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="OpenID"
                    ),
                ),
                (
                    "unionid",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="UnionID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="昵称"
                    ),
                ),
                (
                    "avatar_url",
                    models.URLField(blank=True, null=True, verbose_name="头像URL"),
                ),
                (
                    "sex",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="性别(0未知 1男 2女)"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="省份"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="zh_CN", max_length=20, verbose_name="语言"),
                ),
                (
                    "subscribe_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="关注时间"),
                ),
                (
                    "is_subscribed",
                    models.BooleanField(default=True, verbose_name="是否关注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wechat_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联系统用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "微信用户",
                "verbose_name_plural": "微信用户",
                "db_table": "wechat_user",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "文本消息"),
                            ("image", "图片消息"),
                            ("voice", "语音消息"),
                            ("video", "视频消息"),
                            ("event", "事件消息"),
                            ("location", "位置消息"),
                            ("link", "链接消息"),
                        ],
                        max_length=20,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("subscribe", "关注事件"),
                            ("unsubscribe", "取消关注"),
                            ("scan", "扫描带参数二维码"),
                            ("location", "上报地理位置"),
                            ("click", "点击菜单拉取消息"),
                            ("view", "点击菜单跳转链接"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="消息内容"),
                ),
                (
                    "media_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="媒体ID"
                    ),
                ),
                (
                    "recognition",
                    models.TextField(blank=True, null=True, verbose_name="语音识别结果"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="纬度",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="经度",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="位置信息"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="消息标题"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="链接")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "wechat_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="wechat.wechatuser",
                        verbose_name="微信用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "微信消息",
                "verbose_name_plural": "微信消息",
                "db_table": "wechat_message",
                "ordering": ["-created_at"],
            },
        ),
    ]
