# Generated by Django 4.2.7 on 2026-01-11 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="权限名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="权限代码"),
                ),
                ("module", models.CharField(max_length=50, verbose_name="所属模块")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "权限",
                "verbose_name_plural": "权限",
                "db_table": "core_permission",
                "ordering": ["module", "code"],
            },
        ),
        migrations.CreateModel(
            name="WeChatPayConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配置名称")),
                (
                    "account_type",
                    models.CharField(
                        choices=[("personal", "个人账号"), ("enterprise", "企业对公账户")],
                        default="enterprise",
                        max_length=20,
                        verbose_name="账号类型",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="应用ID(AppID)",
                    ),
                ),
                (
                    "app_secret",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="应用密钥(AppSecret)",
                    ),
                ),
                (
                    "mch_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="商户号(MchID)"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="API密钥"
                    ),
                ),
                (
                    "api_v3_key",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="APIv3密钥"
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="证书序列号"
                    ),
                ),
                (
                    "cert_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="证书路径"
                    ),
                ),
                (
                    "key_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="密钥路径"
                    ),
                ),
                (
                    "notify_url",
                    models.URLField(blank=True, null=True, verbose_name="支付回调地址"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认")),
                ("remarks", models.TextField(blank=True, null=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "微信支付配置",
                "verbose_name_plural": "微信支付配置",
                "db_table": "core_wechat_pay_config",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "超级管理员"),
                    ("admin", "管理员"),
                    ("finance", "财务"),
                    ("receptionist", "前台"),
                    ("engineering", "工程部"),
                    ("owner", "业主"),
                    ("tenant", "租户"),
                ],
                default="owner",
                max_length=20,
                verbose_name="角色",
            ),
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "超级管理员"),
                            ("admin", "管理员"),
                            ("finance", "财务"),
                            ("receptionist", "前台"),
                            ("engineering", "工程部"),
                            ("owner", "业主"),
                            ("tenant", "租户"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("can_view", models.BooleanField(default=True, verbose_name="可查看")),
                ("can_create", models.BooleanField(default=False, verbose_name="可创建")),
                ("can_edit", models.BooleanField(default=False, verbose_name="可编辑")),
                ("can_delete", models.BooleanField(default=False, verbose_name="可删除")),
                ("can_export", models.BooleanField(default=False, verbose_name="可导出")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.permission",
                        verbose_name="权限",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色权限",
                "verbose_name_plural": "角色权限",
                "db_table": "core_role_permission",
                "ordering": ["role", "permission__module"],
                "unique_together": {("role", "permission")},
            },
        ),
    ]
