# Generated by Django 4.2.7 on 2026-01-22 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
        ("payment", "0004_paymentrecord_operator"),
        ("core", "0002_permission_wechatpayconfig_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("payment_reminder", "缴费提醒"),
                            ("payment_overdue", "逾期催缴"),
                            ("maintenance_assigned", "报事派单"),
                            ("maintenance_processing", "报事处理中"),
                            ("maintenance_completed", "报事完成"),
                            ("maintenance_closed", "报事关闭"),
                            ("system_announcement", "系统公告"),
                        ],
                        max_length=50,
                        verbose_name="通知类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="接收人电话"
                    ),
                ),
                (
                    "recipient_openid",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="微信OpenID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待发送"),
                            ("sent", "已发送"),
                            ("failed", "发送失败"),
                            ("read", "已读"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("send_channels", models.JSONField(default=dict, verbose_name="发送渠道")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="阅读时间"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                ("retry_count", models.IntegerField(default=0, verbose_name="重试次数")),
                ("max_retries", models.IntegerField(default=3, verbose_name="最大重试次数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="接收人",
                    ),
                ),
                (
                    "related_bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="payment.paymentbill",
                        verbose_name="关联账单",
                    ),
                ),
                (
                    "related_maintenance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="maintenance.maintenancerequest",
                        verbose_name="关联报事",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统通知",
                "verbose_name_plural": "系统通知",
                "db_table": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "status"],
                        name="notificatio_recipie_d40309_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "status"],
                        name="notificatio_notific_36dad5_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="notificatio_created_c430f0_idx"
                    ),
                ],
            },
        ),
    ]
