# Generated by Django 4.2.7 on 2026-01-06 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("property", "0001_initial"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_number",
                    models.CharField(max_length=50, unique=True, verbose_name="报事编号"),
                ),
                ("reporter", models.CharField(max_length=50, verbose_name="报事人")),
                (
                    "reporter_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electric", "电工"),
                            ("plumbing", "水工"),
                            ("civil", "土木"),
                            ("elevator", "电梯"),
                            ("cleaning", "清洁"),
                            ("security", "安保"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="报事类别",
                    ),
                ),
                ("description", models.TextField(verbose_name="问题描述")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片列表"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待派单"),
                            ("assigned", "已派单"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("closed", "已关闭"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "一般"), ("medium", "紧急"), ("high", "非常紧急")],
                        default="low",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="指派给"
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="派单时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始处理时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "result_images",
                    models.JSONField(blank=True, default=list, verbose_name="处理结果图片"),
                ),
                (
                    "result_description",
                    models.TextField(blank=True, null=True, verbose_name="处理结果说明"),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="评分(1-5)"),
                ),
                (
                    "feedback",
                    models.TextField(blank=True, null=True, verbose_name="用户反馈"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="community.community",
                        verbose_name="所属小区",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_requests",
                        to="property.property",
                        verbose_name="房产",
                    ),
                ),
            ],
            options={
                "verbose_name": "报事记录",
                "verbose_name_plural": "报事记录",
                "db_table": "maintenance_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operator", models.CharField(max_length=50, verbose_name="操作人")),
                ("action", models.CharField(max_length=50, verbose_name="操作类型")),
                ("description", models.TextField(verbose_name="操作说明")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="图片"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="maintenance.maintenancerequest",
                        verbose_name="报事记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "报事处理日志",
                "verbose_name_plural": "报事处理日志",
                "db_table": "maintenance_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
