# Generated by Django 4.2.7 on 2026-01-06 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("property", "0001_initial"),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentBill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(max_length=50, unique=True, verbose_name="账单编号"),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("property", "物业费"),
                            ("public_electric", "公摊电费"),
                            ("water", "水费"),
                            ("parking", "停车费"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="费用类型",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(max_length=20, verbose_name="账期（如：2026-01）"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="应缴金额(元)"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="已缴金额(元)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未缴"),
                            ("partial", "部分缴"),
                            ("paid", "已缴"),
                            ("overdue", "逾期"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="应缴日期")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="缴费时间"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="community.community",
                        verbose_name="所属小区",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="property.owner",
                        verbose_name="业主",
                    ),
                ),
                (
                    "property_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="property.property",
                        verbose_name="房产",
                    ),
                ),
            ],
            options={
                "verbose_name": "缴费账单",
                "verbose_name_plural": "缴费账单",
                "db_table": "payment_bill",
                "ordering": ["-billing_period", "-created_at"],
                "unique_together": {("property_unit", "fee_type", "billing_period")},
            },
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="微信支付交易号"
                    ),
                ),
                (
                    "out_trade_no",
                    models.CharField(max_length=100, unique=True, verbose_name="商户订单号"),
                ),
                ("payer", models.CharField(max_length=50, verbose_name="缴费人")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="缴费金额(元)"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wechat", "微信支付"),
                            ("alipay", "支付宝"),
                            ("cash", "现金"),
                            ("bank_transfer", "银行转账"),
                        ],
                        default="wechat",
                        max_length=20,
                        verbose_name="支付方式",
                    ),
                ),
                ("payment_time", models.DateTimeField(verbose_name="支付时间")),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "成功"), ("refund", "退款"), ("failed", "失败")],
                        default="success",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="退款金额(元)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_records",
                        to="payment.paymentbill",
                        verbose_name="关联账单",
                    ),
                ),
            ],
            options={
                "verbose_name": "缴费记录",
                "verbose_name_plural": "缴费记录",
                "db_table": "payment_record",
                "ordering": ["-payment_time"],
            },
        ),
        migrations.CreateModel(
            name="FeeStandard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="费用名称")),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("property", "物业费"),
                            ("public_electric", "公摊电费"),
                            ("water", "水费"),
                            ("parking", "停车费"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="费用类型",
                    ),
                ),
                (
                    "price_per_square",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="每平米单价(元)"
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("month", "按月"), ("quarter", "按季"), ("year", "按年")],
                        default="month",
                        max_length=20,
                        verbose_name="计费周期",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="费用说明"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_standards",
                        to="community.community",
                        verbose_name="所属小区",
                    ),
                ),
            ],
            options={
                "verbose_name": "物业费标准",
                "verbose_name_plural": "物业费标准",
                "db_table": "payment_fee_standard",
                "ordering": ["community", "fee_type"],
            },
        ),
    ]
