# Generated by Django 4.2.7 on 2026-01-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestandard",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("property", "物业费"),
                    ("public_electric", "公摊电费"),
                    ("water", "水费"),
                    ("parking", "停车费"),
                    ("payable", "应缴费用"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="费用类型",
            ),
        ),
        migrations.AlterField(
            model_name="paymentbill",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("property", "物业费"),
                    ("public_electric", "公摊电费"),
                    ("water", "水费"),
                    ("parking", "停车费"),
                    ("payable", "应缴费用"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="费用类型",
            ),
        ),
    ]
