# Generated by Django 4.2.7 on 2026-01-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_alter_feestandard_fee_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentbill",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wechat", "微信支付"),
                    ("alipay", "支付宝"),
                    ("cash", "现金"),
                    ("bank_transfer", "银行转账"),
                ],
                max_length=20,
                null=True,
                verbose_name="支付方式",
            ),
        ),
    ]
