# Generated by Django 4.2.7 on 2026-01-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_paymentbill_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrecord",
            name="operator",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="操作人"
            ),
        ),
    ]
