# Generated by Django 4.2.7 on 2026-01-06 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="小区名称"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="小区地址")),
                (
                    "total_households",
                    models.IntegerField(default=0, verbose_name="总户数"),
                ),
                (
                    "developer",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="开发商"
                    ),
                ),
                (
                    "property_company",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="物业公司"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="小区描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "小区",
                "verbose_name_plural": "小区",
                "db_table": "community_community",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="楼栋号")),
                (
                    "building_type",
                    models.CharField(
                        choices=[
                            ("high", "高层"),
                            ("multi", "多层"),
                            ("villa", "别墅"),
                            ("commercial", "商业"),
                        ],
                        default="high",
                        max_length=20,
                        verbose_name="楼栋类型",
                    ),
                ),
                (
                    "total_floors",
                    models.IntegerField(blank=True, null=True, verbose_name="总楼层数"),
                ),
                ("total_units", models.IntegerField(default=1, verbose_name="单元数")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="楼栋描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="community.community",
                        verbose_name="所属小区",
                    ),
                ),
            ],
            options={
                "verbose_name": "楼栋",
                "verbose_name_plural": "楼栋",
                "db_table": "community_building",
                "ordering": ["community", "name"],
                "unique_together": {("community", "name")},
            },
        ),
    ]
