# Generated by Django 4.2.7 on 2026-01-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="construction_area",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="建筑面积(㎡)"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="联系人"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系电话"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="green_area",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="绿化面积(㎡)"
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="total_buildings",
            field=models.IntegerField(default=0, verbose_name="楼栋数"),
        ),
    ]
